# PM2.5 训练默认配置

# 数据与批量
num_pred: 24
history_len: 24
batch_size: 16
feature_idx: 0

# 优化参数
learning_rate: 0.0005
epochs: 80

# 模型结构
K: 8
d: 8
L: 3
bn_decay: 0.1
geo_ratio: 0.6
S: 6
num_patterns: 16
time_steps_per_day: 24
spatial_chunk_size: 64

# 预处理文件路径
pattern_path: /tmp/artifacts/pattern_keys.npy
geo_mask_path: /tmp/artifacts/geo_mask.npy
sem_mask_path: /tmp/artifacts/sem_mask.npy
geo_neighbors_path: /tmp/artifacts/geo_neighbors.npz
sem_neighbors_path: /tmp/artifacts/sem_neighbors.npz
